name: Refresh App Token (Reusable)

on:
  workflow_call:
    inputs:
      key-vault-name:
        description: 'The name of the Azure Key Vault'
        type: string
        required: true
      secret-name:
        description: 'The name of the secret in Key Vault'
        type: string
        required: true
    secrets:
      secret-value:
        description: 'The value of the secret to set in Key Vault'
      required: true

jobs:
  delete-and-set-secret:
    steps:
    - name: Delete existing secret ${{ inputs.secret-name }}
      uses: azure/cli@v1
      with:
        inlineScript: |
          # Don't fail this step if purging fails as we want to continue to try and set
          az keyvault secret delete --vault-name ${{ inputs.key-vault-name}} --name ${{ inputs.secret-name }} || true

    - name: Purge existing secret ${{ inputs.secret-name }}
      uses: azure/cli@v1
      with:
        inlineScript: |
          for i in {1..5}; do
            az keyvault secret purge --vault-name ${{ inputs.key-vault-name}} --name ${{ inputs.secret-name }} && true
            if [[ $? -eq 0 ]]; then break; fi
            if [[ $i -ge 5 ]]; then 
              echo "Failed to purge ${{ inputs.secret-name }} from ${{ inputs.key-vault-name}}"
              exit 0 # Don't fail this step if purging fails as we want to continue to try and set
            fi
            echo "Failed to purge ${{ inputs.secret-name }} from ${{ inputs.key-vault-name}}... Retrying after sleeping $i"
            sleep $i
          done

    - name: Set token secret ${{ inputs.secret-name }}
      uses: azure/cli@v1
      with:
        inlineScript: |
          expires_at=$(date -u -d "1 hour" '+%Y-%m-%dT%H:%M:%SZ')
          for i in {1..5}; do
            az keyvault secret set --vault-name ${{ inputs.key-vault-name}} --name ${{ inputs.secret-name }} --value ${{ steps.generate_token.outputs.token }} --expires "$expires_at" && true
            if [[ $? -eq 0 ]]; then break; fi
            if [[ $i -ge 5 ]]; then
              echo "Failed to set ${{ inputs.secret-name }} from ${{ inputs.key-vault-name}}"
              exit $?
            fi
            echo "Failed to set ${{ inputs.secret-name }} from ${{ inputs.key-vault-name}}... Retrying after sleeping $i"
            sleep $i
          done
