name: Refresh App Token

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  id-token: write

env:
  KEY_VAULT_NAME: azure-sdk-github-secrets
  SECRET_NAME: azure-sdk-automation-access-token

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    environment: azure-sdk-automation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Refresh app token and store in Key Vault
      uses: ./.github/actions/refresh-app-token
      with:
        key-vault-name: ${{ env.KEY_VAULT_NAME }}
        secret-name: ${{ env.SECRET_NAME }}
        client-id: 45a289d0-4d69-4ac9-948b-1a0d9cfb08b3
        tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47
        subscription-id: a18897a6-7e44-457d-9260-f2854c0aca42
        app-id: Iv23lio5GQbTbrf7cJTJ
        private-key: ${{ secrets.AZURE_SDK_AUTOMATION_PRIVATE_KEY }}
        owner: Azure
        expiration-hours: 1
