name: Refresh App Token

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  id-token: write

env:
  KEY_VAULT_NAME: azure-sdk-github-secrets
  SECRET_NAME: azure-sdk-automation-access-token

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    environment: azure-sdk-automation

    steps:
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: 45a289d0-4d69-4ac9-948b-1a0d9cfb08b3
        tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47
        subscription-id: a18897a6-7e44-457d-9260-f2854c0aca42

    - name: Generate GitHub App Installation Token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: Iv23lio5GQbTbrf7cJTJ
        private-key: ${{ secrets.AZURE_SDK_AUTOMATION_PRIVATE_KEY }}
        owner: Azure
        skip-token-revoke: true

    - name: Delete existing secret
      uses: azure/cli@v1
      with:
        inlineScript: |
          az keyvault secret delete --vault-name $KEY_VAULT_NAME --name $SECRET_NAME || true

    - name: Purge existing secret
      uses: azure/cli@v1
      with:
        inlineScript: |
          i=1
          while ! az keyvault secret purge --vault-name $KEY_VAULT_NAME --name $SECRET_NAME; do
            if [[ $i -ge 5 ]]; then
              echo "Failed to purge $SECRET_NAME from $KEY_VAULT_NAME"
              break
            fi
            echo "Failed to purge $SECRET_NAME from $KEY_VAULT_NAME... Retrying after sleeping $i"
            sleep $i
            ((i++))
          done

    - name: Set token secret
      uses: azure/cli@v1
      with:
        inlineScript: |
          expires_at=$(date -u -d "1 hour" '+%Y-%m-%dT%H:%M:%SZ')
          az keyvault secret set --vault-name $KEY_VAULT_NAME --name $SECRET_NAME --value ${{ steps.generate_token.outputs.token }} --expires "$expires_at"
